# Generated by Django 6.0.4 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_modified_at', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-added_at', 'display_name'],
            },
        ),
    ]
