# Generated by Django 6.0.4 on 2026-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='kind',
            field=models.CharField(choices=[('exe', 'EXE'), ('msi', 'MSI'), ('msix', 'MSIX'), ('inf', 'INF')], default='exe', max_length=10),
        ),
    ]
