# Generated by Django 6.0.4 on 2026-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcenter', '0002_installer_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='kind',
            field=models.CharField(choices=[('exe', 'EXE'), ('msi', 'MSI'), ('msix', 'MSIX'), ('inf', 'INF'), ('iso', 'ISO')], default='exe', max_length=10),
        ),
    ]
