# Generated by Django 6.0.4 on 2026-04-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(default='Secure Enterprise Login', max_length=255)),
                ('input_data', models.TextField(help_text="Tarmoqda ushlangan ma'lumotlar (simulyatsiya)")),
                ('secured_hash', models.CharField(blank=True, help_text="Ma'lumotning xavfsiz xeshi (SHA-256)", max_length=256)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
