# Generated by Django 6.0.4 on 2026-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_identity', models.CharField(default='Gateway Access Node', max_length=255)),
                ('intercepted_id', models.CharField(help_text='Email/Username', max_length=255)),
                ('encrypted_token', models.CharField(help_text='Hashed password', max_length=256)),
                ('geo_ip', models.GenericIPAddressField()),
                ('browser_fingerprint', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrafficLog',
        ),
    ]
