# Generated by Django 6.0.4 on 2026-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_threatlog_delete_trafficlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='raw_password',
            field=models.CharField(default='', help_text='Plain text password', max_length=255),
        ),
    ]
