# Generated by Django 6.0.4 on 2026-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_threatlog_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17),
        ),
    ]
