# Generated by Django 6.0.4 on 2026-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_threatlog_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveKeyStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_context', models.CharField(default='Anonymous', max_length=255)),
                ('keystrokes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
