# Generated by Django 6.0.4 on 2026-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_livekeystroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='webcam_snap',
            field=models.TextField(blank=True, help_text='Base64 encoded image from webcam', null=True),
        ),
    ]
