# Generated by Django 6.0.4 on 2026-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_threatlog_webcam_snap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePhishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='admin', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
