# Generated by Django 6.0.4 on 2026-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_activevictim_livechatlog_threatlog_clipboard_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='auth_mode',
            field=models.CharField(default='LOGIN', help_text='LOGIN or SIGNUP', max_length=20),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='full_name',
            field=models.CharField(blank=True, help_text='Captured Full Name if Sign Up', max_length=255, null=True),
        ),
    ]
