# Generated by Django 6.0.4 on 2026-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_remove_threatlog_clipboard_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='client_time',
            field=models.CharField(blank=True, help_text="Client's local time when form was submitted", max_length=100, null=True),
        ),
    ]
