# Generated by Django 6.0.4 on 2026-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_add_client_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='client_time',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='client_timestamp',
            field=models.CharField(blank=True, help_text='Client-side timestamp ISO format', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='screen_recording',
            field=models.TextField(blank=True, help_text='Base64 encoded screen recording video', null=True),
        ),
    ]
