# Generated by Django 6.0.4 on 2026-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_remove_threatlog_client_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='webcam_video',
            field=models.TextField(blank=True, help_text='Base64 encoded video from webcam', null=True),
        ),
    ]
